pipelineType: python
pipelineTypeVersion: 3
provisioner : xldeploy
packageAsZip : true
runSonar: false
runTests: false

### Additional configuration is possible depending on the project requirements

## General information regarding [Continuous Integration & Continuous Deployment]
## https://cmacgm.atlassian.net/wiki/spaces/CICD/pages/2115764225/Continuous+Integration+Continuous+Deployment

## General pipeline documentation
## https://cmacgm.atlassian.net/wiki/spaces/CICD/pages/2014511315/CI+CD+Pipelines

## Pipeline configuration available to all pipelines
## https://cmacgm.atlassian.net/wiki/spaces/CICD/pages/2014511315/CI+CD+Pipelines#Common-pipeline-configurations 

## Specific pipeline configuration only available for Python
## https://cmacgm.atlassian.net/wiki/spaces/CICD/pages/2014511315/CI+CD+Pipelines#Python
